// <auto-generated />
using System;
using Grimoire.Library.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Grimoire.Library.Migrations
{
    [DbContext(typeof(GrimoireDbContext))]
    [Migration("20260715112734_AddTasteAnchors")]
    partial class AddTasteAnchors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grimoire.Library.Models.Artist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<DateTime?>("AbstractCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("abstract_checked_at");

                    b.Property<string>("AbstractUrl")
                        .HasColumnType("text")
                        .HasColumnName("abstract_url");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateOnly?>("DeathDate")
                        .HasColumnType("date")
                        .HasColumnName("death_date");

                    b.Property<string>("DeathPlace")
                        .HasColumnType("text")
                        .HasColumnName("death_place");

                    b.Property<int?>("DissolvedYear")
                        .HasColumnType("integer")
                        .HasColumnName("dissolved_year");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<int?>("FormedYear")
                        .HasColumnType("integer")
                        .HasColumnName("formed_year");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Links")
                        .HasColumnType("jsonb")
                        .HasColumnName("links");

                    b.Property<int?>("Listeners")
                        .HasColumnType("integer")
                        .HasColumnName("listeners");

                    b.PrimitiveCollection<string[]>("LyricalThemes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("lyrical_themes");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<DateTime?>("MetalArchivesCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metal_archives_checked_at");

                    b.Property<string>("MetalArchivesGenre")
                        .HasColumnType("text")
                        .HasColumnName("metal_archives_genre");

                    b.Property<int?>("MetalArchivesId")
                        .HasColumnType("integer")
                        .HasColumnName("metal_archives_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("text")
                        .HasColumnName("preview_url");

                    b.Property<string>("Rank")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("rank");

                    b.Property<string>("SortName")
                        .HasColumnType("text")
                        .HasColumnName("sort_name");

                    b.PrimitiveCollection<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<double?>("XyX")
                        .HasColumnType("double precision")
                        .HasColumnName("xy_x");

                    b.Property<double?>("XyY")
                        .HasColumnType("double precision")
                        .HasColumnName("xy_y");

                    b.HasKey("Id")
                        .HasName("pk_artists");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_artists_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasDatabaseName("ix_artists_mbid");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_artists_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.ArtistEdge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BeginDate")
                        .HasColumnType("date")
                        .HasColumnName("begin_date");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FromId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_id");

                    b.PrimitiveCollection<string[]>("Instruments")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("instruments");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ToId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_id");

                    b.HasKey("Id")
                        .HasName("pk_artist_edges");

                    b.HasIndex("ToId")
                        .HasDatabaseName("ix_artist_edges_to_id");

                    b.HasIndex("FromId", "ToId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("ix_artist_edges_from_id_to_id_kind");

                    b.ToTable("artist_edges", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.CorpusStat", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ArtistCount")
                        .HasColumnType("integer")
                        .HasColumnName("artist_count");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at");

                    b.Property<Vector>("MeanEmbedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("mean_embedding");

                    b.HasKey("Id")
                        .HasName("pk_corpus_stats");

                    b.ToTable("corpus_stats", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.CoverVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CoverRecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("cover_recording_id");

                    b.Property<Guid>("OriginalRecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_recording_id");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relation");

                    b.HasKey("Id")
                        .HasName("pk_cover_versions");

                    b.HasIndex("CoverRecordingId")
                        .HasDatabaseName("ix_cover_versions_cover_recording_id");

                    b.HasIndex("OriginalRecordingId", "CoverRecordingId")
                        .IsUnique()
                        .HasDatabaseName("ix_cover_versions_original_recording_id_cover_recording_id");

                    b.ToTable("cover_versions", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.Credit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<float>("Confidence")
                        .HasColumnType("real")
                        .HasColumnName("confidence");

                    b.Property<string>("Instrument")
                        .HasColumnType("text")
                        .HasColumnName("instrument");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("boolean")
                        .HasColumnName("is_guest");

                    b.Property<Guid?>("RecordingId")
                        .HasColumnType("uuid")
                        .HasColumnName("recording_id");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_credits");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_credits_artist_id");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_credits_release_id");

                    b.ToTable("credits", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.GrimoireUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_labels");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasDatabaseName("ix_labels_mbid");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.PushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("p256dh");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_push_subscriptions_user_id");

                    b.ToTable("push_subscriptions", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.Recording", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("LengthMs")
                        .HasColumnType("integer")
                        .HasColumnName("length_ms");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("release_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_recordings");

                    b.HasIndex("Mbid")
                        .HasDatabaseName("ix_recordings_mbid");

                    b.HasIndex("ReleaseId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_recordings_release_id_position");

                    b.ToTable("recordings", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<string>("CoverUrl")
                        .HasColumnType("text")
                        .HasColumnName("cover_url");

                    b.Property<Guid?>("LabelId")
                        .HasColumnType("uuid")
                        .HasColumnName("label_id");

                    b.Property<Guid>("Mbid")
                        .HasColumnType("uuid")
                        .HasColumnName("mbid");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_releases_artist_id");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ix_releases_label_id");

                    b.HasIndex("Mbid")
                        .IsUnique()
                        .HasDatabaseName("ix_releases_mbid");

                    b.ToTable("releases", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.Rite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<float>("Risk")
                        .HasColumnType("real")
                        .HasColumnName("risk");

                    b.Property<DateTimeOffset>("ServedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("served_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_rites");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_rites_artist_id");

                    b.HasIndex("UserId", "ArtistId")
                        .HasDatabaseName("ix_rites_user_id_artist_id");

                    b.ToTable("rites", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.TasteAnchor", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ArtistId")
                        .HasColumnType("uuid")
                        .HasColumnName("artist_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("UserId", "ArtistId")
                        .HasName("pk_taste_anchors");

                    b.HasIndex("ArtistId")
                        .HasDatabaseName("ix_taste_anchors_artist_id");

                    b.ToTable("taste_anchors", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.TasteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DepthScore")
                        .HasColumnType("integer")
                        .HasColumnName("depth_score");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_taste_snapshots");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_taste_snapshots_user_id_created_at");

                    b.ToTable("taste_snapshots", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.UserTaste", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("DepthScore")
                        .HasColumnType("integer")
                        .HasColumnName("depth_score");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<Vector>("Repulsion")
                        .HasColumnType("vector(768)")
                        .HasColumnName("repulsion");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_user_taste");

                    b.ToTable("user_taste", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Grimoire.Library.Models.ArtistEdge", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Artist", "From")
                        .WithMany()
                        .HasForeignKey("FromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artist_edges_artists_from_id");

                    b.HasOne("Grimoire.Library.Models.Artist", "To")
                        .WithMany()
                        .HasForeignKey("ToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_artist_edges_artists_to_id");

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("Grimoire.Library.Models.CoverVersion", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Recording", "Cover")
                        .WithMany()
                        .HasForeignKey("CoverRecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cover_versions_recordings_cover_recording_id");

                    b.HasOne("Grimoire.Library.Models.Recording", "Original")
                        .WithMany()
                        .HasForeignKey("OriginalRecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cover_versions_recordings_original_recording_id");

                    b.Navigation("Cover");

                    b.Navigation("Original");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Credit", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credits_artists_artist_id");

                    b.HasOne("Grimoire.Library.Models.Release", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_credits_releases_release_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.PushSubscription", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscriptions_asp_net_users_user_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Recording", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Release", "Release")
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recordings_releases_release_id");

                    b.Navigation("Release");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Release", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Artist", "Artist")
                        .WithMany("Releases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_releases_artists_artist_id");

                    b.HasOne("Grimoire.Library.Models.Label", "Label")
                        .WithMany("Releases")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_releases_labels_label_id");

                    b.Navigation("Artist");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Rite", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rites_artists_artist_id");

                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rites_asp_net_users_user_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.TasteAnchor", b =>
                {
                    b.HasOne("Grimoire.Library.Models.Artist", null)
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_taste_anchors_artists_artist_id");

                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_taste_anchors_asp_net_users_user_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.TasteSnapshot", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_taste_snapshots_asp_net_users_user_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.UserTaste", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithOne()
                        .HasForeignKey("Grimoire.Library.Models.UserTaste", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_taste_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Grimoire.Library.Models.GrimoireUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Artist", b =>
                {
                    b.Navigation("Releases");
                });

            modelBuilder.Entity("Grimoire.Library.Models.Label", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
